apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: core-bank
  labels:
    app: account-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
        version: v1
    spec:
      containers:
      - name: account-service
        image: account-service:latest # Build from Account-Service/Dockerfile
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgres://corebankuser:corebankpass@postgres:5432/corebankdb?sslmode=disable"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "corebankuser"
        - name: POSTGRES_PASSWORD
          value: "corebankpass"
        - name: POSTGRES_DB
          value: "corebankdb"
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres 5432; do echo "Waiting for Postgres..."; sleep 5; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
